### ISSUE TITLE
Document forwarded_allow_ips for gunicorn

### ISSUE THREAD

**Issue by ab** [lyft/confidant#50]
Anyone standing up confidant behind load balancers will likely need to set `--forwarded-allow-ips=*` or similar in order for wsgi to trust the `X-Forwarded-*` headers and get the real client's address and scheme.

**Comment by ryan-lane** [comment]
Thanks for the report!

**Comment by alsmola** [comment]
I ran into this issue and setting the environment variable `FORWARDED_ALLOW_IPS` to `*` didn't work, but adding the `--forwarded-allow-ips=*` command line flag did.

**Comment by ryan-lane** [comment]
Ah. That's disappointing. I'll need to verify how to handle this with environment vars. I'll make sure the docs recommend the flag.

**Comment by egeland** [comment]
Can this please be included in the Docker image as the default?

**Comment by ryan-lane** [comment]
Yeah, I think that makes sense, since we always assume we're behind a load
balancer.

**Comment by ryan-lane** [comment]
To followup a bit on @egeland's comment, we're upgrading gunicorn to support the env var for FORWARDED_ALLOW_IPS and are recommending setting that, rather than changing the docker command to set this by default. Mostly we're doing it this way because if we make it the default it's more difficult to disable, if you want to disable it, and it's better to tend towards security. Gunicorn upgrade is [here](https://github.com/lyft/confidant/pull/138), and will be in 1.9.

**Comment by egeland** [comment]
Looks good in docker image 1.9.0 ✅
